report_to:
  - "wandb"

run_name: null

wandb:
  project: "instruction-tuning"
  entity: null
  tags:
    - "sft"
    - "parallel"
  notes: ""

weave:
  enabled: false
  project: null
  print_call_link: false
  implicitly_patch_integrations: false
